### ISSUE TITLE
[Android] Problems with Core in Jelly Bean

### ISSUE THREAD

**Issue by Quickgold74** [libretro-mirrors/scummvm#21]
When I try to load the core RA shows No Core, this issue happend to me in Android Jelly Bean 4.1

**Comment by diablodiab** [comment]
I'm thinking it's caused by the recent addition of vorbis support to the ScummVM core. This requires an Android OS that supports Vorbis and Jelly Bean might be too old for that.

I'll put together a pull request for the buildbot that builds two scummvm cores, one with vorbis support and one without.

**Comment by inactive123** [comment]
Are there dynamic linking dependencies on libvorbis now then for Android?

In that case, if it sacrifices backwards compatibility, that's bad. I'd rather we statically bake in ogg vorbis then. This was done for the Dinothawr core, so you could take a look at that and possibly just copy over the libvorbis code there and bring it over to our scummvm repo.

Check out this:

https://github.com/libretro/Dinothawr/tree/master/ogg

**Comment by diablodiab** [comment]
Yes, it's dynamic linking. There's also dynamic linking to zlib, which could also be the problem.

I'll take a look at the Dinothawr core and see if I can incorporate it into the ScummVM core.

**Comment by diablodiab** [comment]
I believe the problem is caused by dynamic linking zlib - I'll submit a pull request shortly which bakes zlib into the ScummVM core. Hopefully this will fix the problem.

**Comment by diablodiab** [comment]
Please check if you still experience crashes when the next nightly ScummVM core is available.

**Comment by Quickgold74** [comment]
Thanks, I will check later because I have problem installing the last nightly something about a different signature and if I uninstall the old RA version (2016-01-21) I can't install 2016-01-22, finish with an error (this happend with the nighly and the f-droid last version), I will try later with the next nightly, there are other cores that it doesn't works like scummvm in jelly bean (I will report on their respective github).

**Comment by andres-asm** [comment]
It won't be fixed by the next build, the signatures are here to stay, basically now all the builds use the same signature so you can move from google play to f-droid without reinstalling.
It's a bit of a pain in the ass but it had to be done at some point

**Comment by Quickgold74** [comment]
Oh so, Do I have to uninstall my version, install from Google Play and install the nightly from f-droid (or the new one from the page)? because I did unistall my version and I did try installing directly the nightly build and it gave me an error.

**Comment by andres-asm** [comment]
Uninstall then fdroid directly if you want nighlites

**Comment by Quickgold74** [comment]
Still ScummVM shows "No Core" with the Iast nightly, I thought that the problem is relative to the toolchain like Radius said before.

**Comment by Quickgold74** [comment]
Today still shows "No Core" in Android 4.1.2 (I remember this was fix it)
